// Code generated by mockery v2.14.0. DO NOT EDIT.

package ipfs

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, resourceID
func (_m *MockGateway) Get(ctx context.Context, resourceID string) ([]byte, error) {
	ret := _m.Called(ctx, resourceID)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReader provides a mock function with given fields: ctx, resourceID
func (_m *MockGateway) GetReader(ctx context.Context, resourceID string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, resourceID)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockGateway interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGateway(t mockConstructorTestingTNewMockGateway) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
